### ISSUE TITLE
How install npm 

### ISSUE THREAD

**Issue by riddik14** [chaeplin/homebridge-mqtt-nest-thermostat#3]
Hi, how I can install homebridge-mqtt-nest-thermostat on raspberry? Npm?

**Comment by vsidlu** [comment]
hi,

navigate to your /usr/lib/node_modules folder. git clone this plugin. navigate to this new cloned folder and sudo npm install. this will add dependencies. then edit confg.json file and you should have new accessory.

**Comment by riddik14** [comment]
Started Node.js HomeKit Server.
[2018-7-23 18:15:09] Loaded config.json with 48 accessories and 3 platforms.
[2018-7-23 18:15:09] ---
[2018-7-23 18:15:09] Loaded plugin: homebridge-bravia
[2018-7-23 18:15:09] Registering platform 'homebridge-bravia.BraviaPlatform'
[2018-7-23 18:15:09] ---
[2018-7-23 18:15:10] Loaded plugin: homebridge-camera-ffmpeg
[2018-7-23 18:15:10] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2018-7-23 18:15:10] ---
[2018-7-23 18:15:10] Loaded plugin: homebridge-config-ui-x
[2018-7-23 18:15:10] Registering platform 'homebridge-config-ui-x.config'
[2018-7-23 18:15:10] ---
[2018-7-23 18:15:10] Loaded plugin: homebridge-gpio-sensors
[2018-7-23 18:15:10] Registering accessory 'homebridge-gpio-sensors.GPIOSensors'
[2018-7-23 18:15:10] ---
[2018-7-23 18:15:11] Loaded plugin: homebridge-http-sprinkler
[2018-7-23 18:15:11] Registering accessory 'homebridge-http-sprinkler.HttpSprinkler'
[2018-7-23 18:15:11] ---
[2018-7-23 18:15:11] Loaded plugin: homebridge-max-temperature-log
[2018-7-23 18:15:11] Registering accessory 'homebridge-max-temperature-log.max-temperature-log'
[2018-7-23 18:15:11] ---
[2018-7-23 18:15:11] Loaded plugin: homebridge-min-temperature-log
[2018-7-23 18:15:11] Registering accessory 'homebridge-min-temperature-log.min-temperature-log'
[2018-7-23 18:15:11] ---
[2018-7-23 18:15:12] Loaded plugin: homebridge-mqtt
homebridge API version: 2.2
[2018-7-23 18:15:12] Registering platform 'homebridge-mqtt.mqtt'
[2018-7-23 18:15:12] ---
[2018-7-23 18:15:12] Loaded plugin: homebridge-mqtt-humidity
[2018-7-23 18:15:12] Registering accessory 'homebridge-mqtt-humidity.mqtt-humidity'
[2018-7-23 18:15:12] ---
[2018-7-23 18:15:12] Loaded plugin: homebridge-mqtt-humidity-tasmota
[2018-7-23 18:15:12] Registering accessory 'homebridge-mqtt-humidity-tasmota.mqtt-humidity-tasmota'
[2018-7-23 18:15:12] ---
[2018-7-23 18:15:13] Loaded plugin: homebridge-mqtt-nestthermostat
[2018-7-23 18:15:13] Registering accessory 'homebridge-mqtt-nestthermostat.mqtt-nestthermostat'
[2018-7-23 18:15:13] ---
[2018-7-23 18:15:13] Loaded plugin: homebridge-mqtt-pressure
[2018-7-23 18:15:13] Registering accessory 'homebridge-mqtt-pressure.mqtt-pressure'
[2018-7-23 18:15:13] ---
[2018-7-23 18:15:13] Loaded plugin: homebridge-mqtt-security
[2018-7-23 18:15:13] Registering accessory 'homebridge-mqtt-security.Homebridge-MQTT-Security'
[2018-7-23 18:15:13] ---
[2018-7-23 18:15:14] Loaded plugin: homebridge-mqtt-statelessswitch
[2018-7-23 18:15:14] Registering accessory 'homebridge-mqtt-statelessswitch.mqtt-statelessswitch'
[2018-7-23 18:15:14] ---
[2018-7-23 18:15:14] Loaded plugin: homebridge-mqtt-switch-tasmota
[2018-7-23 18:15:14] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[2018-7-23 18:15:14] ---
[2018-7-23 18:15:14] Loaded plugin: homebridge-mqtt-temperature
[2018-7-23 18:15:14] Registering accessory 'homebridge-mqtt-temperature.mqtt-temperature'
[2018-7-23 18:15:14] ---
[2018-7-23 18:15:14] Loaded plugin: homebridge-mqtt-temperature-and-humidity-log-tasmota
[2018-7-23 18:15:14] Registering accessory 'homebridge-mqtt-temperature-and-humidity-log-tasmota.mqtt-temperature-and-humidity-log-tasmota'
[2018-7-23 18:15:14] ---
[2018-7-23 18:15:15] Loaded plugin: homebridge-mqtt-temperature-log-tasmota
[2018-7-23 18:15:15] Registering accessory 'homebridge-mqtt-temperature-log-tasmota.mqtt-temperature-log-tasmota'
[2018-7-23 18:15:15] ---
[2018-7-23 18:15:15] Loaded plugin: homebridge-mqttswitch
[2018-7-23 18:15:15] Registering accessory 'homebridge-mqttswitch.mqttswitch'
[2018-7-23 18:15:15] ---
[2018-7-23 18:15:15] Loaded plugin: homebridge-pi-thermostat
[2018-7-23 18:15:15] Registering accessory 'homebridge-pi-thermostat.Thermostat'
[2018-7-23 18:15:15] ---
[2018-7-23 18:15:15] Loaded plugin: homebridge-pir-motion-sensor
[2018-7-23 18:15:15] Registering accessory 'homebridge-motion-sensor.Motion Sensor'
[2018-7-23 18:15:15] ---
[2018-7-23 18:15:15] Loaded plugin: homebridge-raspberrypi-temperature
[2018-7-23 18:15:15] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[2018-7-23 18:15:15] ---
[2018-7-23 18:15:16] Loaded plugin: homebridge-sonytvremote
[2018-7-23 18:15:16] Registering accessory 'homebridge-sonytvremote.SonyTV'
[2018-7-23 18:15:16] ---
[2018-7-23 18:15:16] Loaded plugin: homebridge-weather-station-extended
[2018-7-23 18:15:16] Registering platform 'homebridge-wunderground-extended.WeatherStation'
[2018-7-23 18:15:17] ---
[2018-7-23 18:15:17] Loaded plugin: homebridge-mqtt-nest-thermostat-master
/usr/local/lib/node_modules/homebridge/lib/api.js:80
    throw new Error("Attempting to register an accessory '" + fullName + "' which has already been registered!");
          ^
Error: Attempting to register an accessory 'homebridge-mqtt-nestthermostat.mqtt-nestthermostat' which has already been registered!
    at API.registerAccessory (/usr/local/lib/node_modules/homebridge/lib/api.js:80:11)
    at Plugin.module.exports [as initializer] (/usr/local/node_modules/homebridge-mqtt-nest-thermostat-master/index.js:138:18)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:166:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:140:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.





 {
          "accessory":                 "mqtt-nestthermostat",
          "name":                      "mqtt-nest-thermostat",
          "url":                       "mqtt://localhost",
          "username":                  "admin",
          "password":                  "mimmo",
          "caption":                   "mqtt-nest-thermostat",
          "topics": {
                 "set":                "cmnd/testthermostat/power",
                 "get":                "stat/testthermostat/power"
        }
      },


Where I have do a error?

**Comment by vsidlu** [comment]
i see two mqtt-nest-thermostat plugins installed - 

first - [2018-7-23 18:15:13] Loaded plugin: homebridge-mqtt-nestthermostat
[2018-7-23 18:15:13] Registering accessory 'homebridge-mqtt-nestthermostat.mqtt-nestthermostat'

and second crashing - [2018-7-23 18:15:17] Loaded plugin: homebridge-mqtt-nest-thermostat-master

i am not sure but you can try to remove one of them and check what happens.

**Comment by riddik14** [comment]
I have remove the plugin mqtt nest and now homebridge work. Is only 1 plugin but is releved 2 times

**Comment by riddik14** [comment]
I have cloned in folder, installed but not have remove the clone. The clone do delete?

**Comment by vsidlu** [comment]
in folder /usr/lib/node_modules you need to have only one mqtt nest folder. see also if in this folder you have node_module folder with dependencies.

**Comment by riddik14** [comment]
Ok. Afte install i’ll Remove the clone and try. Thank u

**Comment by riddik14** [comment]
Ok. Work. My error is to be copy zip extract in /usr/lib/node_module. Now I try to install from download folder. Now is ok

**Comment by riddik14** [comment]
Ok. Work. My error is to be copy zip extract in /usr/lib/node_module. Now I try to install from download folder. Now is ok
